### PR TITLE
Pull review for the-benchmarker

### PR DESCRIPTION
**Pull request by waghanza**
Hi @swlkr,

Thanks for contributing to https://github.com/the-benchmarker/web-frameworks.

Instead of a _classical_ review, I've made this `PR` to give you my recommendation

The purpose is to keep this project consistency.

As  `clojure` is a **new** language in the project, I wish to add a linter to ensure code readability. After search, I've found https://joker-lang.org

What do you think of it ?

Regards,

### CODE REVIEW

**Comment by swlkr** [comment]
Yeah, that's what I use, joker is aces

**Comment by swlkr** [comment]
Hey just a heads up, clojure is actually version 1.10.1, i shortened it to 1.10 because i didn't see other languages using semantic, but I noticed in the output it says clojure `1.1`

**Comment by waghanza** [comment]
Nice notice :+1: 

I think it's due to internal conversion, on it ...

**Comment by waghanza** [comment]
Hi @swlkr,

I've made a quick and dirty fix for that.  :tada: 

Thanks for reporting.

**Pull request closed without merging**
